### ISSUE TITLE
foot change

### ISSUE THREAD

**Issue by Freecey** [r-rocket-team/dev-rest#65]
change to our team
![Screenshot from 2021-01-20 19-50-38](https://user-images.githubusercontent.com/71413240/105221130-f6280680-5b58-11eb-897f-b1a5e68e480a.png)

**Comment by Freecey** [comment]
and change email contact to contact@devrest.me

**Comment by Freecey** [comment]
+ add link to github organisation

**Comment by Marmouz82** [comment]
c'est fait
